import type {
  ContentGenerationProvider,
  GeneratedUnit,
  ParsedSyllabus,
  WorkbookAnalysis,
} from './types';

/** Everything one AuthoredTermContent module supplies for a single (className, subject,
 * termLabel) run -- the same content shape a live LLM-backed provider would eventually produce,
 * just authored by hand (or by an agent reading the syllabus directly) instead of generated by
 * an API call at run time. See scripts/generate-curriculum-term.ts for how this gets loaded and
 * handed to generateCurriculumTerm(). */
export interface AuthoredTermContent {
  parsedSyllabus: ParsedSyllabus;
  /** Keyed by the matching SyllabusTopicNode.id in parsedSyllabus.topicTree -- generateUnit below
   * looks up by the topic it's asked to generate, exactly like a real provider would, so an
   * authored module that's missing a topic's content fails loudly instead of silently. */
  units: Record<string, GeneratedUnit>;
  workbookAnalysis?: WorkbookAnalysis;
}

/** Implements ContentGenerationProvider by looking up pre-authored content instead of calling an
 * LLM -- generateCurriculumTerm()'s own orchestration (pacing, upsert logic, UNIQUE-constraint
 * handling, calculation verification, step-ordering validation) runs completely unchanged against
 * it, exactly as it would against a real API-backed provider later. This is the rollout path for
 * getting real syllabus content in now without waiting on that provider to exist -- see
 * NotConfiguredProvider's own comment for the alternative this replaces for this initial pass. */
export class StaticContentGenerationProvider implements ContentGenerationProvider {
  constructor(private readonly content: AuthoredTermContent) {}

  async parseSyllabus(): Promise<ParsedSyllabus> {
    return this.content.parsedSyllabus;
  }

  async analyzeWorkbook(): Promise<WorkbookAnalysis> {
    return this.content.workbookAnalysis ?? { masterySignals: [] };
  }

  async generateUnit(input: { topic: { id: string } }): Promise<GeneratedUnit> {
    const unit = this.content.units[input.topic.id];
    if (!unit) {
      throw new Error(
        `StaticContentGenerationProvider has no authored unit for topic id "${input.topic.id}" -- ` +
          `add it to the AuthoredTermContent module's units map (available: ${Object.keys(this.content.units).join(', ') || 'none'}).`
      );
    }
    return unit;
  }
}
