import type { ClassScheduleSeedEntry } from './class-schedule';

/** Extracted from the school's real weekly timetable spreadsheet (Jadwal_Primary_1.xlsx,
 * uploaded 2026-08-08) via the one-time "Import school timetable" button on
 * /admin/teaching/schedule. class_name values here (Primary / Secondary / Early Years &
 * Kindergarten) are a best guess matching the spreadsheet's own band labels — correct them
 * in this file (or just edit/remove the imported rows afterward) if the school's actual
 * Child Card class_name values differ. No teacher is set on any row; assign teachers
 * per slot afterward via the admin UI. All rows are in_person — the source schedule had no
 * online classes. */
export const SCHOOL_TIMETABLE_SEED: Record<string, ClassScheduleSeedEntry[]> = {
  'Primary': [
    { dayOfWeek: 'monday', startTime: '08:30', endTime: '09:15', subject: 'Morning Routine' },
    { dayOfWeek: 'tuesday', startTime: '08:30', endTime: '09:15', subject: 'Homeroom time' },
    { dayOfWeek: 'wednesday', startTime: '08:30', endTime: '09:15', subject: 'Homeroom time' },
    { dayOfWeek: 'thursday', startTime: '08:30', endTime: '09:15', subject: 'Homeroom Time' },
    { dayOfWeek: 'friday', startTime: '08:30', endTime: '09:15', subject: 'PE' },
    { dayOfWeek: 'monday', startTime: '09:15', endTime: '10:00', subject: 'Mathematics' },
    { dayOfWeek: 'tuesday', startTime: '09:15', endTime: '10:00', subject: 'Mathematics' },
    { dayOfWeek: 'wednesday', startTime: '09:15', endTime: '10:00', subject: 'Mathematics' },
    { dayOfWeek: 'thursday', startTime: '09:15', endTime: '10:00', subject: 'Mathematics' },
    { dayOfWeek: 'friday', startTime: '09:15', endTime: '10:00', subject: 'Phonics' },
    { dayOfWeek: 'monday', startTime: '10:10', endTime: '10:55', subject: 'English' },
    { dayOfWeek: 'tuesday', startTime: '10:10', endTime: '10:55', subject: 'English' },
    { dayOfWeek: 'wednesday', startTime: '10:10', endTime: '10:55', subject: 'Phonics' },
    { dayOfWeek: 'thursday', startTime: '10:10', endTime: '10:55', subject: 'English' },
    { dayOfWeek: 'friday', startTime: '10:10', endTime: '10:55', subject: 'Civic' },
    { dayOfWeek: 'monday', startTime: '10:55', endTime: '11:10', subject: 'Art' },
    { dayOfWeek: 'monday', startTime: '11:10', endTime: '12:00', subject: 'Science' },
    { dayOfWeek: 'tuesday', startTime: '11:10', endTime: '12:00', subject: 'Global Perspective' },
    { dayOfWeek: 'wednesday', startTime: '11:10', endTime: '12:00', subject: 'Science' },
    { dayOfWeek: 'thursday', startTime: '11:10', endTime: '12:00', subject: 'PBL' },
    { dayOfWeek: 'friday', startTime: '11:10', endTime: '12:00', subject: 'Bahasa Indonesia' },
    { dayOfWeek: 'monday', startTime: '12:00', endTime: '13:30', subject: 'Lunch Time' },
    { dayOfWeek: 'tuesday', startTime: '12:00', endTime: '13:30', subject: 'Lunch Time' },
    { dayOfWeek: 'wednesday', startTime: '12:00', endTime: '13:30', subject: 'Lunch Time' },
    { dayOfWeek: 'thursday', startTime: '12:00', endTime: '13:30', subject: 'Lunch Time' },
    { dayOfWeek: 'friday', startTime: '12:00', endTime: '13:30', subject: 'Lunch Time' },
    { dayOfWeek: 'monday', startTime: '13:30', endTime: '15:30', subject: 'Craft / Football' },
    { dayOfWeek: 'tuesday', startTime: '13:30', endTime: '15:30', subject: 'Swimming / Gymnastic' },
    { dayOfWeek: 'wednesday', startTime: '13:30', endTime: '15:30', subject: 'Surfing / Beach Time' },
    { dayOfWeek: 'thursday', startTime: '13:30', endTime: '15:30', subject: 'Art / Music' },
    { dayOfWeek: 'friday', startTime: '13:30', endTime: '15:30', subject: 'Gardening / Padel' },
  ],
  'Secondary': [
    { dayOfWeek: 'monday', startTime: '08:30', endTime: '09:15', subject: 'Morning Routine' },
    { dayOfWeek: 'tuesday', startTime: '08:30', endTime: '09:15', subject: 'Science' },
    { dayOfWeek: 'wednesday', startTime: '08:30', endTime: '09:15', subject: 'Science' },
    { dayOfWeek: 'thursday', startTime: '08:30', endTime: '09:15', subject: 'Bahasa' },
    { dayOfWeek: 'friday', startTime: '08:30', endTime: '09:15', subject: 'Science' },
    { dayOfWeek: 'monday', startTime: '09:15', endTime: '10:00', subject: 'Global Perspectives' },
    { dayOfWeek: 'tuesday', startTime: '09:15', endTime: '10:00', subject: 'English' },
    { dayOfWeek: 'wednesday', startTime: '09:15', endTime: '10:00', subject: 'Science' },
    { dayOfWeek: 'thursday', startTime: '09:15', endTime: '10:00', subject: 'Visual Art' },
    { dayOfWeek: 'friday', startTime: '09:15', endTime: '10:00', subject: 'Economics' },
    { dayOfWeek: 'monday', startTime: '10:10', endTime: '10:55', subject: 'English' },
    { dayOfWeek: 'tuesday', startTime: '10:10', endTime: '10:55', subject: 'Economics' },
    { dayOfWeek: 'wednesday', startTime: '10:10', endTime: '10:55', subject: 'Mathematics' },
    { dayOfWeek: 'thursday', startTime: '10:10', endTime: '10:55', subject: 'English' },
    { dayOfWeek: 'friday', startTime: '10:10', endTime: '10:55', subject: 'English' },
    { dayOfWeek: 'monday', startTime: '11:10', endTime: '12:00', subject: 'Mathematics' },
    { dayOfWeek: 'tuesday', startTime: '11:10', endTime: '12:00', subject: 'Mathematics' },
    { dayOfWeek: 'wednesday', startTime: '11:10', endTime: '12:00', subject: 'Bahasa' },
    { dayOfWeek: 'thursday', startTime: '11:10', endTime: '12:00', subject: 'Global Perspective' },
    { dayOfWeek: 'friday', startTime: '11:10', endTime: '12:00', subject: 'Mathematics' },
    { dayOfWeek: 'monday', startTime: '12:00', endTime: '13:30', subject: 'Lunch Time' },
    { dayOfWeek: 'tuesday', startTime: '12:00', endTime: '13:30', subject: 'Lunch Time' },
    { dayOfWeek: 'wednesday', startTime: '12:00', endTime: '13:30', subject: 'Lunch Time' },
    { dayOfWeek: 'thursday', startTime: '12:00', endTime: '13:30', subject: 'Lunch Time' },
    { dayOfWeek: 'friday', startTime: '12:00', endTime: '13:30', subject: 'Lunch Time' },
    { dayOfWeek: 'monday', startTime: '13:30', endTime: '15:30', subject: 'Craft & Football' },
    { dayOfWeek: 'tuesday', startTime: '13:30', endTime: '15:30', subject: 'Swimming / Gymnastic' },
    { dayOfWeek: 'wednesday', startTime: '13:30', endTime: '15:30', subject: 'Surfing & Beach' },
    { dayOfWeek: 'thursday', startTime: '13:30', endTime: '15:30', subject: 'Art / Music / Craft' },
    { dayOfWeek: 'friday', startTime: '13:30', endTime: '15:30', subject: 'Gardening / Padel' },
  ],
  'Early Years & Kindergarten': [
    { dayOfWeek: 'monday', startTime: '08:30', endTime: '09:00', subject: 'Morning Circle' },
    { dayOfWeek: 'tuesday', startTime: '08:30', endTime: '09:00', subject: 'Morning Circle' },
    { dayOfWeek: 'wednesday', startTime: '08:30', endTime: '09:00', subject: 'Morning Circle' },
    { dayOfWeek: 'thursday', startTime: '08:30', endTime: '09:00', subject: 'Morning Circle' },
    { dayOfWeek: 'friday', startTime: '08:30', endTime: '09:00', subject: 'Morning Circle' },
    { dayOfWeek: 'monday', startTime: '09:00', endTime: '09:30', subject: 'Outdoor Play' },
    { dayOfWeek: 'tuesday', startTime: '09:00', endTime: '09:30', subject: 'Mathematics' },
    { dayOfWeek: 'wednesday', startTime: '09:00', endTime: '09:30', subject: 'Mathematics' },
    { dayOfWeek: 'thursday', startTime: '09:00', endTime: '09:30', subject: 'Mathematics' },
    { dayOfWeek: 'friday', startTime: '09:00', endTime: '09:30', subject: 'Phonics' },
    { dayOfWeek: 'monday', startTime: '09:30', endTime: '10:00', subject: 'English' },
    { dayOfWeek: 'tuesday', startTime: '09:30', endTime: '10:00', subject: 'Phonics' },
    { dayOfWeek: 'wednesday', startTime: '09:30', endTime: '10:00', subject: 'English' },
    { dayOfWeek: 'thursday', startTime: '09:30', endTime: '10:00', subject: 'Sensory Play' },
    { dayOfWeek: 'friday', startTime: '09:30', endTime: '10:00', subject: 'English' },
    { dayOfWeek: 'monday', startTime: '10:00', endTime: '10:30', subject: 'Snack Time' },
    { dayOfWeek: 'tuesday', startTime: '10:00', endTime: '10:30', subject: 'Snack Time' },
    { dayOfWeek: 'wednesday', startTime: '10:00', endTime: '10:30', subject: 'Snack Time' },
    { dayOfWeek: 'thursday', startTime: '10:00', endTime: '10:30', subject: 'Snack Time' },
    { dayOfWeek: 'friday', startTime: '10:00', endTime: '10:30', subject: 'Snack Time' },
    { dayOfWeek: 'monday', startTime: '10:30', endTime: '11:00', subject: 'Art with Ms Tia' },
    { dayOfWeek: 'tuesday', startTime: '10:30', endTime: '11:00', subject: 'Writing' },
    { dayOfWeek: 'wednesday', startTime: '10:30', endTime: '11:00', subject: 'Phonics' },
    { dayOfWeek: 'thursday', startTime: '10:30', endTime: '11:00', subject: 'Art with Ms Tia' },
    { dayOfWeek: 'friday', startTime: '10:30', endTime: '11:00', subject: 'Writing' },
    { dayOfWeek: 'monday', startTime: '11:00', endTime: '11:30', subject: 'Science' },
    { dayOfWeek: 'tuesday', startTime: '11:00', endTime: '11:30', subject: 'Sensory Play' },
    { dayOfWeek: 'wednesday', startTime: '11:00', endTime: '11:30', subject: 'Science' },
    { dayOfWeek: 'thursday', startTime: '11:00', endTime: '11:30', subject: 'Bahasa Indonesia' },
    { dayOfWeek: 'friday', startTime: '11:00', endTime: '11:30', subject: 'Music & Movement' },
    { dayOfWeek: 'monday', startTime: '12:00', endTime: '13:00', subject: 'Lunch Time' },
    { dayOfWeek: 'tuesday', startTime: '12:00', endTime: '13:00', subject: 'Lunch Time' },
    { dayOfWeek: 'wednesday', startTime: '12:00', endTime: '13:00', subject: 'Lunch Time' },
    { dayOfWeek: 'thursday', startTime: '12:00', endTime: '13:00', subject: 'Lunch Time' },
    { dayOfWeek: 'friday', startTime: '12:00', endTime: '13:00', subject: 'Lunch Time' },
    { dayOfWeek: 'monday', startTime: '13:30', endTime: '15:30', subject: 'Craft & Football' },
    { dayOfWeek: 'tuesday', startTime: '13:30', endTime: '15:30', subject: 'Swimming / Gymnastic' },
    { dayOfWeek: 'wednesday', startTime: '13:30', endTime: '15:30', subject: 'Surfing & Beach' },
    { dayOfWeek: 'thursday', startTime: '13:30', endTime: '15:30', subject: 'Art / Music / Craft' },
    { dayOfWeek: 'friday', startTime: '13:30', endTime: '15:30', subject: 'Gardening / Padel' },
  ],
};
